import type { TaskItem, ActivityItem } from "./types";

export const mockTasks: TaskItem[] = [
  {
    id: "1",
    title: "Implement log streaming",
    specPath: ".agent/specs/todo/1-log-streaming/spec.md",
    projectId: "project-1",
    status: "pending",
  },
  {
    id: "2",
    title: "Add workflow list view",
    specPath: ".agent/specs/todo/2-workflow-list/spec.md",
    projectId: "project-1",
    status: "pending",
  },
  {
    id: "3",
    title: "Redesign sidebar layout",
    specPath: ".agent/specs/todo/3-implement-sidebar-redesign/spec.md",
    projectId: "project-1",
    status: "pending",
  },
  {
    id: "4",
    title: "Add real-time notifications",
    specPath: ".agent/specs/todo/4-notifications/spec.md",
    projectId: "project-1",
    status: "pending",
  },
  {
    id: "5",
    title: "Optimize database queries",
    specPath: ".agent/specs/todo/5-db-optimization/spec.md",
    projectId: "project-1",
    status: "pending",
  },
  {
    id: "6",
    title: "Implement dark mode toggle",
    specPath: ".agent/specs/todo/6-dark-mode/spec.md",
    projectId: "project-2",
    status: "pending",
  },
];

export const mockActivities: ActivityItem[] = [
  {
    id: "workflow-1",
    type: "workflow",
    name: "CI/CD Pipeline",
    status: "running",
    updatedAt: "2025-11-08T15:45:00Z",
    projectId: "project-1",
  },
  {
    id: "session-1",
    type: "session",
    name: "Implementing user authentication",
    status: "running",
    updatedAt: "2025-11-08T15:30:00Z",
    projectId: "project-1",
  },
  {
    id: "workflow-2",
    type: "workflow",
    name: "Run integration tests",
    status: "running",
    updatedAt: "2025-11-08T15:15:00Z",
    projectId: "project-1",
  },
  {
    id: "session-2",
    type: "session",
    name: "Fixing sidebar navigation bug",
    status: "running",
    updatedAt: "2025-11-08T15:00:00Z",
    projectId: "project-1",
  },
  {
    id: "workflow-3",
    type: "workflow",
    name: "Deploy to staging",
    status: "running",
    updatedAt: "2025-11-08T14:45:00Z",
    projectId: "project-1",
  },
  {
    id: "session-3",
    type: "session",
    name: "Debug authentication flow",
    status: "completed",
    updatedAt: "2025-11-08T14:30:00Z",
    projectId: "project-1",
  },
  {
    id: "workflow-4",
    type: "workflow",
    name: "Database Migration",
    status: "completed",
    updatedAt: "2025-11-08T14:00:00Z",
    projectId: "project-1",
  },
  {
    id: "session-4",
    type: "session",
    name: "Refactor component structure",
    status: "failed",
    updatedAt: "2025-11-08T13:30:00Z",
    projectId: "project-1",
  },
  {
    id: "workflow-5",
    type: "workflow",
    name: "Lint and format code",
    status: "completed",
    updatedAt: "2025-11-08T13:00:00Z",
    projectId: "project-1",
  },
  {
    id: "session-5",
    type: "session",
    name: "Add unit tests for API",
    status: "completed",
    updatedAt: "2025-11-08T12:30:00Z",
    projectId: "project-1",
  },
  {
    id: "workflow-6",
    type: "workflow",
    name: "Build and package app",
    status: "pending",
    updatedAt: "2025-11-08T12:00:00Z",
    projectId: "project-1",
  },
  {
    id: "session-6",
    type: "session",
    name: "Update documentation",
    status: "running",
    updatedAt: "2025-11-08T11:45:00Z",
    projectId: "project-2",
  },
  {
    id: "workflow-7",
    type: "workflow",
    name: "Security audit",
    status: "running",
    updatedAt: "2025-11-08T11:30:00Z",
    projectId: "project-2",
  },
  {
    id: "session-7",
    type: "session",
    name: "Optimize image loading",
    status: "completed",
    updatedAt: "2025-11-08T11:00:00Z",
    projectId: "project-2",
  },
  {
    id: "session-8",
    type: "session",
    name: "Workflow-attached session",
    status: "running",
    updatedAt: "2025-11-08T15:45:00Z",
    projectId: "project-1",
    workflowRunId: "workflow-1", // Should be filtered out
  },
];
