packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - bcrypt
  - better-sqlite3
  - canvas
  - esbuild
  - node-pty
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
