// @ts-nocheck
import * as __fd_glob_49 from "../content/docs/reference/steps/phase.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/reference/steps/log.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/reference/steps/index.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/reference/steps/git.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/reference/steps/cli.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/reference/steps/artifact.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/reference/steps/annotation.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/reference/steps/ai.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/reference/steps/agent.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/examples/advanced/workspace-management.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/examples/advanced/multi-phase-workflows.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/examples/advanced/multi-agent-workflows.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/examples/advanced/artifact-management.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/troubleshooting/workflow-failures.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/troubleshooting/connection-problems.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/troubleshooting/common-errors.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/reference/slash-commands.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/reference/configuration.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/reference/cli.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/reference/agentcmd-workflows.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/reference/agent-cli-sdk.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/getting-started/quick-start.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/getting-started/installation.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/getting-started/how-it-works.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/getting-started/first-workflow.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/getting-started/access-anywhere.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/examples/workflow-definition.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/examples/type-safe-arguments.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/examples/spec-implementation.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/examples/error-handling.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/examples/data-processing.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/examples/custom-slash-command.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/examples/context-sharing.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/examples/basic-automation.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/concepts/workflow-runs.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/concepts/workflow-definitions.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/concepts/steps.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/concepts/specs.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/concepts/sessions.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/concepts/phases.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/concepts/agents.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/index.mdx?collection=docs"
import { default as __fd_glob_7 } from "../content/docs/reference/steps/meta.json?collection=docs"
import { default as __fd_glob_6 } from "../content/docs/examples/advanced/meta.json?collection=docs"
import { default as __fd_glob_5 } from "../content/docs/reference/meta.json?collection=docs"
import { default as __fd_glob_4 } from "../content/docs/troubleshooting/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/getting-started/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/examples/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/concepts/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { fromConfig } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = fromConfig<typeof Config>();

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "concepts/meta.json": __fd_glob_1, "examples/meta.json": __fd_glob_2, "getting-started/meta.json": __fd_glob_3, "troubleshooting/meta.json": __fd_glob_4, "reference/meta.json": __fd_glob_5, "examples/advanced/meta.json": __fd_glob_6, "reference/steps/meta.json": __fd_glob_7, }, {"index.mdx": __fd_glob_8, "concepts/agents.mdx": __fd_glob_9, "concepts/phases.mdx": __fd_glob_10, "concepts/sessions.mdx": __fd_glob_11, "concepts/specs.mdx": __fd_glob_12, "concepts/steps.mdx": __fd_glob_13, "concepts/workflow-definitions.mdx": __fd_glob_14, "concepts/workflow-runs.mdx": __fd_glob_15, "examples/basic-automation.mdx": __fd_glob_16, "examples/context-sharing.mdx": __fd_glob_17, "examples/custom-slash-command.mdx": __fd_glob_18, "examples/data-processing.mdx": __fd_glob_19, "examples/error-handling.mdx": __fd_glob_20, "examples/spec-implementation.mdx": __fd_glob_21, "examples/type-safe-arguments.mdx": __fd_glob_22, "examples/workflow-definition.mdx": __fd_glob_23, "getting-started/access-anywhere.mdx": __fd_glob_24, "getting-started/first-workflow.mdx": __fd_glob_25, "getting-started/how-it-works.mdx": __fd_glob_26, "getting-started/installation.mdx": __fd_glob_27, "getting-started/quick-start.mdx": __fd_glob_28, "reference/agent-cli-sdk.mdx": __fd_glob_29, "reference/agentcmd-workflows.mdx": __fd_glob_30, "reference/cli.mdx": __fd_glob_31, "reference/configuration.mdx": __fd_glob_32, "reference/slash-commands.mdx": __fd_glob_33, "troubleshooting/common-errors.mdx": __fd_glob_34, "troubleshooting/connection-problems.mdx": __fd_glob_35, "troubleshooting/workflow-failures.mdx": __fd_glob_36, "examples/advanced/artifact-management.mdx": __fd_glob_37, "examples/advanced/multi-agent-workflows.mdx": __fd_glob_38, "examples/advanced/multi-phase-workflows.mdx": __fd_glob_39, "examples/advanced/workspace-management.mdx": __fd_glob_40, "reference/steps/agent.mdx": __fd_glob_41, "reference/steps/ai.mdx": __fd_glob_42, "reference/steps/annotation.mdx": __fd_glob_43, "reference/steps/artifact.mdx": __fd_glob_44, "reference/steps/cli.mdx": __fd_glob_45, "reference/steps/git.mdx": __fd_glob_46, "reference/steps/index.mdx": __fd_glob_47, "reference/steps/log.mdx": __fd_glob_48, "reference/steps/phase.mdx": __fd_glob_49, });