// @ts-nocheck
import * as __fd_glob_42 from "../content/docs/reference/workflow-steps/phase.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/reference/workflow-steps/log.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/reference/workflow-steps/git.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/reference/workflow-steps/cli-step.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/reference/workflow-steps/artifact.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/reference/workflow-steps/annotation.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/reference/workflow-steps/ai.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/reference/workflow-steps/agent.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/concepts/workflows/workflow-triggers.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/concepts/workflows/workflow-steps.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/concepts/workflows/workflow-runs.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/concepts/workflows/workflow-phases.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/concepts/workflows/workflow-definitions.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/reference/webhooks.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/reference/slash-commands.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/reference/configuration.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/reference/cli.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/reference/agentcmd-workflows.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/getting-started/quick-start.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/getting-started/installation.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/getting-started/how-it-works.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/getting-started/first-workflow.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/getting-started/access-anywhere.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/concepts/spec-task-system.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/concepts/spec-driven-development.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/concepts/slash-commands.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/concepts/sessions.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/concepts/agents.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/examples/type-safe-slash-commands.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/examples/type-safe-arguments.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/examples/recursive-implement-review.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/examples/mcp-integration.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/examples/implement-and-review.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/examples/context-sharing.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/examples/advanced-recursive-implement-review.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/index.mdx?collection=docs"
import { default as __fd_glob_6 } from "../content/docs/reference/workflow-steps/meta.json?collection=docs"
import { default as __fd_glob_5 } from "../content/docs/concepts/workflows/meta.json?collection=docs"
import { default as __fd_glob_4 } from "../content/docs/reference/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/examples/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/getting-started/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/concepts/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { fromConfig } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = fromConfig<typeof Config>();

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "concepts/meta.json": __fd_glob_1, "getting-started/meta.json": __fd_glob_2, "examples/meta.json": __fd_glob_3, "reference/meta.json": __fd_glob_4, "concepts/workflows/meta.json": __fd_glob_5, "reference/workflow-steps/meta.json": __fd_glob_6, }, {"index.mdx": __fd_glob_7, "examples/advanced-recursive-implement-review.mdx": __fd_glob_8, "examples/context-sharing.mdx": __fd_glob_9, "examples/implement-and-review.mdx": __fd_glob_10, "examples/mcp-integration.mdx": __fd_glob_11, "examples/recursive-implement-review.mdx": __fd_glob_12, "examples/type-safe-arguments.mdx": __fd_glob_13, "examples/type-safe-slash-commands.mdx": __fd_glob_14, "concepts/agents.mdx": __fd_glob_15, "concepts/sessions.mdx": __fd_glob_16, "concepts/slash-commands.mdx": __fd_glob_17, "concepts/spec-driven-development.mdx": __fd_glob_18, "concepts/spec-task-system.mdx": __fd_glob_19, "getting-started/access-anywhere.mdx": __fd_glob_20, "getting-started/first-workflow.mdx": __fd_glob_21, "getting-started/how-it-works.mdx": __fd_glob_22, "getting-started/installation.mdx": __fd_glob_23, "getting-started/quick-start.mdx": __fd_glob_24, "reference/agentcmd-workflows.mdx": __fd_glob_25, "reference/cli.mdx": __fd_glob_26, "reference/configuration.mdx": __fd_glob_27, "reference/slash-commands.mdx": __fd_glob_28, "reference/webhooks.mdx": __fd_glob_29, "concepts/workflows/workflow-definitions.mdx": __fd_glob_30, "concepts/workflows/workflow-phases.mdx": __fd_glob_31, "concepts/workflows/workflow-runs.mdx": __fd_glob_32, "concepts/workflows/workflow-steps.mdx": __fd_glob_33, "concepts/workflows/workflow-triggers.mdx": __fd_glob_34, "reference/workflow-steps/agent.mdx": __fd_glob_35, "reference/workflow-steps/ai.mdx": __fd_glob_36, "reference/workflow-steps/annotation.mdx": __fd_glob_37, "reference/workflow-steps/artifact.mdx": __fd_glob_38, "reference/workflow-steps/cli-step.mdx": __fd_glob_39, "reference/workflow-steps/git.mdx": __fd_glob_40, "reference/workflow-steps/log.mdx": __fd_glob_41, "reference/workflow-steps/phase.mdx": __fd_glob_42, });