import { Package } from "lucide-react";
import {
  Empty,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
  EmptyDescription,
} from "@/client/components/ui/empty";
import { ArtifactCard } from "@/client/components/ArtifactCard";
import type { WorkflowRun } from "@/client/pages/projects/workflows/types";

interface ArtifactsTabProps {
  run: WorkflowRun;
}

export function ArtifactsTab({ run }: ArtifactsTabProps) {
  const artifacts = run.artifacts || [];

  if (artifacts.length === 0) {
    return (
      <Empty>
        <EmptyHeader>
          <EmptyMedia variant="icon">
            <Package />
          </EmptyMedia>
          <EmptyTitle>No artifacts available</EmptyTitle>
          <EmptyDescription>
            Artifacts generated by this workflow will appear here
          </EmptyDescription>
        </EmptyHeader>
      </Empty>
    );
  }

  return (
    <div className="space-y-4">
      {artifacts.map((artifact) => (
        <ArtifactCard
          key={artifact.id}
          name={artifact.name}
          fileType={artifact.file_type}
          sizeBytes={artifact.size_bytes}
          onDownload={() => {
            // TODO: Implement artifact download
            console.log("Download artifact:", artifact.id);
          }}
        />
      ))}
    </div>
  );
}
