import { describe, it, expect } from "vitest";
import { generateSlashCommandTypesCode } from "./generateSlashCommandTypes";
import type { CommandDefinition } from "../types/slash-commands-internal";

describe("generateSlashCommandTypesCode", () => {
  it("should generate types for multiple namespaced commands with arguments", () => {
    const commands: CommandDefinition[] = [
      {
        name: "/cmd:generate-prd",
        description: "Generate PRD",
        arguments: [
          { name: "feature-name", required: true },
          { name: "context", required: false },
        ],
      },
      {
        name: "/cmd:implement-spec",
        description: "Implement spec",
        arguments: [{ name: "spec-name-or-path", required: true }],
      },
    ];

    const code = generateSlashCommandTypesCode(commands);

    // Should have header
    expect(code).toContain("// Auto-generated by workflow-sdk generate-slash-types");

    // Should have union type
    expect(code).toContain('export type SlashCommandName = "/cmd:generate-prd" | "/cmd:implement-spec"');

    // Should have args interface with correct optional markers (properties are quoted)
    expect(code).toContain('"/cmd:generate-prd": { "feature-name": string; "context"?: string }');
    expect(code).toContain('"/cmd:implement-spec": { "spec-name-or-path": string }');

    // Should have buildSlashCommand function
    expect(code).toContain("export function buildSlashCommand");
  });

  it("should generate types for commands with no arguments", () => {
    const commands: CommandDefinition[] = [
      {
        name: "/cmd:check",
        description: "Run checks",
        arguments: [],
      },
    ];

    const code = generateSlashCommandTypesCode(commands);

    expect(code).toContain('"/cmd:check": Record<string, never>');
  });

  it("should handle empty commands array", () => {
    const code = generateSlashCommandTypesCode([]);

    expect(code).toContain("export type SlashCommandName = never");
    expect(code).toContain("No commands found");
  });

  it("should generate valid TypeScript", () => {
    const commands: CommandDefinition[] = [
      {
        name: "/cmd:test-cmd",
        description: "Test",
        arguments: [
          { name: "arg1", required: true },
          { name: "arg2", required: false },
        ],
      },
    ];

    const code = generateSlashCommandTypesCode(commands);

    // Check for TypeScript syntax elements
    expect(code).toMatch(/export type SlashCommandName = /);
    expect(code).toMatch(/export interface SlashCommandArgs/);
    expect(code).toMatch(/export function buildSlashCommand/);
  });

  it("should properly mark optional vs required arguments", () => {
    const commands: CommandDefinition[] = [
      {
        name: "/cmd:mixed",
        description: "Mixed args",
        arguments: [
          { name: "required1", required: true },
          { name: "optional1", required: false },
          { name: "required2", required: true },
          { name: "optional2", required: false },
        ],
      },
    ];

    const code = generateSlashCommandTypesCode(commands);

    // Required args should NOT have ? (properties are quoted)
    expect(code).toContain('"required1": string');
    expect(code).toContain('"required2": string');

    // Optional args should have ?
    expect(code).toContain('"optional1"?: string');
    expect(code).toContain('"optional2"?: string');
  });

  it("should quote property names with hyphens in both mapping and interfaces", () => {
    const commands: CommandDefinition[] = [
      {
        name: "/commit-and-push",
        description: "Commit and push changes",
        arguments: [
          { name: "base-branch", required: true },
          { name: "commit-message", required: false },
        ],
      },
      {
        name: "/simple-cmd",
        description: "Simple command",
        arguments: [
          { name: "normalArg", required: true },
        ],
      },
    ];

    const code = generateSlashCommandTypesCode(commands);

    // SlashCommandArgs mapping should quote properties with hyphens
    expect(code).toContain('"/commit-and-push": { "base-branch": string; "commit-message"?: string }');
    expect(code).toContain('"/simple-cmd": { "normalArg": string }');

    // Individual Args interface should quote properties with hyphens
    expect(code).toContain('export interface CommitAndPushArgs {');
    expect(code).toContain('  "base-branch": string;');
    expect(code).toContain('  "commit-message"?: string;');

    // Properties without hyphens should not be quoted in interfaces
    expect(code).toContain('export interface SimpleCmdArgs {');
    expect(code).toContain('  normalArg: string;');

    // Verify it's valid TypeScript syntax
    expect(code).not.toContain('base-branch: string'); // Should be quoted
    expect(code).not.toContain('commit-message?: string'); // Should be quoted
  });
});
